location = ['Rome', 'Antartica', 'Denmark', 'Germany', 'Africa', 'China']
print (location)
print (sorted(location))
print (location)
print(sorted(location, reverse=True))
print (location)
location.sort()
print (location)
print (len(location))
location.append('egypt')
print (location)
location.remove("Rome")
print (location)
popped = location.pop(2)
print (popped)
